@startuml provider

class zcl_amp_strategist{
  + provide_metrics()
}

class zcl_amp_metrics_system <<zif_amp_metrics_collector>>
class zcl_amp_metrics_performance <<zif_amp_metrics_collector>>
class zcl_amp_metrics_ <<zif_amp_metrics_collector>>

interface zif_amp_metrics_collector{
  get_metrics
}

zcl_amp_strategist o-- metrics_collector

metrics_collector <|-- zcl_amp_metrics_system
metrics_collector <|-- zcl_amp_metrics_performance
metrics_collector <|-- zcl_amp_metrics_

@enduml

@startuml scraper


interface if_http_extension{
  handle_request
}
interface zif_amp_converter{
  convert
}

class zcl_amp_scraper <<if_http_extension>>

class zcl_amp_conv_http_json <<zif_amp_converter>>
class zcl_amp_conv_prom_keyvalue <<zif_amp_converter>>
class zcl_amp_metrics_ <<zif_amp_converter>>

zcl_amp_scraper --> zcl_amp_conv_http_json
zcl_amp_scraper --> zcl_amp_conv_prom_keyvalue
zcl_amp_scraper --> zcl_amp_metrics_

@enduml