@startuml component_diagram

Job - metricsProvider
HTTP - SICF
metricsProvider --> metricsStore
SICF --> metricsStore 
package "metricsProvider" {
  [metrics collector] 
}

package "SICF" {
  [metrics converter]
}

database "metricsStore" { 

}
@enduml