@startuml component_diagram

Job - metricsProvider
HTTP - metricsScraper
metricsProvider --> metricsStore
metricsScraper --> metricsStore 
package "metricsProvider" {
  [metrics collector] 
}

package "metricsScraper" {
  [metrics converter]
}

database "metricsStore" { 

}
@enduml